/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view.playerCharacter;

import classes_de_conexao.Conexao;
import java.io.File;
import java.io.FileInputStream;
import javax.swing.JOptionPane;
import java.sql.*;

/**
 *
 * @author Ramon Souza
 */
public class CadastrarPlayerCharacter extends javax.swing.JFrame {

    private int id_player;

    //instanciar objeto para o fluxo de bytes
    private FileInputStream fis;

    //variavel global para armazenar o tamanho da imagem(bytes)
    private int tamanho;

    /**
     * Creates new form CadastrarPlayerCharacter
     */
    public CadastrarPlayerCharacter() {
        initComponents();
    }
    
    public CadastrarPlayerCharacter(int id) {
        initComponents();
        this.id_player = id;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBox1 = new javax.swing.JCheckBox();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tfNomePers = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        checkBoxCavaleiro = new javax.swing.JCheckBox();
        checkBoxMago = new javax.swing.JCheckBox();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        jCheckBox1.setText("jCheckBox1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(800, 600));
        jPanel1.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));
        jPanel2.setPreferredSize(new java.awt.Dimension(360, 380));
        jPanel2.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Olá ....");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(153, 6, 48, 25);

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Nome do personagem:");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(10, 260, 170, 16);
        jPanel2.add(tfNomePers);
        tfNomePers.setBounds(10, 290, 190, 22);

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Escolha o tipo de seu personagem:");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(90, 40, 183, 16);

        checkBoxCavaleiro.setText("Cavaleiro");
        jPanel2.add(checkBoxCavaleiro);
        checkBoxCavaleiro.setBounds(50, 220, 90, 20);

        checkBoxMago.setText("Mago");
        jPanel2.add(checkBoxMago);
        checkBoxMago.setBounds(250, 220, 60, 20);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cavaleiro .jpg"))); // NOI18N
        jPanel2.add(jLabel5);
        jLabel5.setBounds(20, 80, 150, 120);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/mago .jpg"))); // NOI18N
        jPanel2.add(jLabel7);
        jLabel7.setBounds(200, 80, 150, 120);

        jButton1.setBackground(new java.awt.Color(51, 204, 0));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Criar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1);
        jButton1.setBounds(220, 290, 72, 23);

        jButton2.setBackground(new java.awt.Color(255, 0, 0));
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Voltar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2);
        jButton2.setBounds(10, 350, 80, 23);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(220, 110, 360, 380);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/star.jpg"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 800, 600);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if (checkBoxCavaleiro.isSelected() && checkBoxMago.isSelected()) {
            JOptionPane.showMessageDialog(null, "Selecione apenas um tipo de personagem");
            return;
        }

        //TODO criar playercharacter
        //TODO adicionar na fila
        
        //banco de dados
        try {
            Connection con = Conexao.faz_conexao();

            if (checkBoxCavaleiro.isSelected()) {
                // convertendo imagem
                try {
                    File arquivo = new File("src/images/cavaleiro .jpg");
                    fis = new FileInputStream(arquivo);
                    tamanho = (int) arquivo.length();
                } catch (Exception e) {
                    System.out.println(e);
                }
                
                String sql = "insert into dados_playercharacter (player_id, character_name, nivel, vida_maxima, vida_atual, manaMaxima, manaAtual, type, foto, agilidade, forca) "
                        + "values (?, ?, 1, 10, 10, 0, 0, 'Cavaleiro', ?, 2, 5)";
                
                

                PreparedStatement stmt = con.prepareStatement(sql);
                stmt.setInt(1, id_player);
                stmt.setString(2, tfNomePers.getText());
                stmt.setBlob(3, fis, tamanho);
                stmt.execute();
                stmt.close();
            }

            if (checkBoxMago.isSelected()) {
                 try {
                    File arquivo = new File("src/images/mago .jpg");
                    fis = new FileInputStream(arquivo);
                    tamanho = (int) arquivo.length();
                } catch (Exception e) {
                    System.out.println(e);
                }
                
                String sql = "insert into dados_playercharacter (player_id, character_name, nivel, vida_maxima, vida_atual, manaMaxima, manaAtual, type, foto, agilidade, forca) "
                        + "values (?, ?, 1, 8, 8, 5, 2, 'Mago', ?, 5, 2)";

                PreparedStatement stmt = con.prepareStatement(sql);
                stmt.setInt(1, getId_player());
                stmt.setString(2, tfNomePers.getText());
                stmt.setBlob(3, fis, tamanho);
                stmt.execute();
                stmt.close();

            }

            con.close();
            JOptionPane.showMessageDialog(null, "Personagem cadastrado com sucesso!");
            tfNomePers.setText("");
            checkBoxCavaleiro.setSelected(false);
            checkBoxMago.setSelected(false);

            HomeCharacter LoginFrame = new HomeCharacter(id_player);
            LoginFrame.setVisible(true);
            LoginFrame.pack();
            LoginFrame.setLocationRelativeTo(null);
            this.dispose();

        } catch (SQLException e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        HomeCharacter LoginFrame = new HomeCharacter(id_player);
        LoginFrame.setVisible(true);
        LoginFrame.pack();
        LoginFrame.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastrarPlayerCharacter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastrarPlayerCharacter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastrarPlayerCharacter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastrarPlayerCharacter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastrarPlayerCharacter().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox checkBoxCavaleiro;
    private javax.swing.JCheckBox checkBoxMago;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField tfNomePers;
    // End of variables declaration//GEN-END:variables

    // getters and setters
    public int getId_player() {
        return id_player;
    }

    public void setId_player(int id_player) {
        this.id_player = id_player;
    }

}
